import { Router, type Request, type Response } from "express";
import { createCipheriv, createHash, createHmac, timingSafeEqual } from "node:crypto";
import { Buffer } from "node:buffer";
import { BASE_PATH } from "../../lib/base-path.js";

const router = Router();
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36";
const TIMEOUT = 30000;
const CHUNK = 2 * 1024 * 1024;
const SECRET = process.env.SESSION_SECRET || "development-only-stream-secret";
const ABYSS_SUFFIXES = [".sssrr.org", ".abysscdn.com"];
const ZEPHYR_CDN_HOST_RE = /^s\d+\.zn-grid\d+\.top$/i;

function origin(req: Request) { const proto=(req.headers["x-forwarded-proto"] as string)||req.protocol||"https"; const host=(req.headers["x-forwarded-host"] as string)||req.headers.host||""; return `${proto}://${host}`; }
function appUrl(req: Request, path: string) { return `${origin(req)}${BASE_PATH}${path}`; }
function abs(u:string,b:string) { try{return new URL(u,b).toString()}catch{return u} }
async function fetchUp(url:string, init:RequestInit={}) { const c=new AbortController(); const t=setTimeout(()=>c.abort(),TIMEOUT); try{return await fetch(url,{...init,signal:c.signal,headers:{"User-Agent":UA,...(init.headers||{})}})}finally{clearTimeout(t)} }
function rewriteResource(value:string, source:string, req:Request) {
  const absolute = abs(value.trim(), source);
  try {
    const parsed = new URL(absolute);
    if (ZEPHYR_CDN_HOST_RE.test(parsed.hostname) && parsed.pathname.startsWith("/f/")) {
      return `${appUrl(req, "/animeworld/hls-cdn")}/${parsed.hostname}${parsed.pathname}${parsed.search}`;
    }
    if (parsed.hostname.toLowerCase() === "play.zephyrix.org" && parsed.pathname.startsWith("/hls/")) {
      return `${appUrl(req, "/animeworld/proxy")}?url=${encodeURIComponent(absolute)}`;
    }
  } catch {}
  return value;
}
function rewrite(text:string, source:string, req:Request) {
  let out=text.replace(/^([^#\s][^\s]*)$/gm,l=>rewriteResource(l, source, req));
  return out.replace(/URI="([^"]+)"/g,(_,u)=>`URI="${rewriteResource(u, source, req)}"`);
}

router.get("/animeworld/proxy", async(req:Request,res:Response)=>{ const url=String(req.query.url||""); if(!/^https?:\/\//i.test(url)){res.status(400).send("Invalid url");return;} try{const r=await fetchUp(url,{headers:{Referer:"https://play.zephyrix.org/"}}); if(!r.ok){res.status(r.status).send(`Upstream error: ${r.status}`);return;} const ct=r.headers.get("content-type")||""; const body=await r.arrayBuffer(); const bytes=Buffer.from(body); const isPlaylist=ct.includes("mpegurl")||ct.includes("m3u8")||/\.m3u8(?:\?|$)/i.test(url)||bytes.toString("utf8",0,32).trimStart().startsWith("#EXTM3U"); res.setHeader("Access-Control-Allow-Origin","*"); res.setHeader("Access-Control-Allow-Methods","GET, HEAD, OPTIONS"); res.setHeader("Access-Control-Allow-Headers","*"); if(isPlaylist){res.setHeader("Content-Type","application/vnd.apple.mpegurl");res.send(rewrite(bytes.toString("utf8"),url,req));return;} if(ct)res.setHeader("Content-Type",ct); if(r.headers.get("content-length"))res.setHeader("Content-Length",r.headers.get("content-length")!); if(r.headers.get("content-range"))res.setHeader("Content-Range",r.headers.get("content-range")!); if(r.headers.get("accept-ranges"))res.setHeader("Accept-Ranges",r.headers.get("accept-ranges")!); res.status(r.status).send(bytes); }catch(e){res.status(502).send(`Proxy error: ${(e as Error).message}`)} });

router.use("/animeworld/hls-cdn", async(req:Request,res:Response,next)=>{ const marker="/animeworld/hls-cdn/"; const pathStart=req.originalUrl.indexOf(marker); if(pathStart<0){next();return;} const encodedPath=req.originalUrl.slice(pathStart+marker.length).split("?")[0]; const parts=encodedPath.split("/"); if(parts.length<2){res.status(400).send("Invalid CDN path");return;} const host=decodeURIComponent(parts.shift()||""); const path=parts.map(part=>decodeURIComponent(part)).join("/"); if(!ZEPHYR_CDN_HOST_RE.test(host)||!path.startsWith("f/")){res.status(400).send("Invalid CDN host");return;} if(req.method==="OPTIONS"){res.status(204).set({"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, HEAD, OPTIONS","Access-Control-Allow-Headers":"*"}).end();return;} try{const upstreamUrl=`https://${host}/${path}${req.originalUrl.includes("?")?`?${req.originalUrl.split("?")[1]}`:""}`; const headers:Record<string,string>={Referer:"https://play.zephyrix.org/"}; if(req.headers.range)headers.Range=req.headers.range; const upstream=await fetchUp(upstreamUrl,{method:req.method==="HEAD"?"HEAD":"GET",headers}); if(!upstream.ok){res.status(upstream.status).send(`Upstream error: ${upstream.status}`);return;} for(const header of ["content-length","content-range","accept-ranges","cache-control","etag"]){const value=upstream.headers.get(header);if(value)res.setHeader(header,value);} res.status(upstream.status).set({"Content-Type":"video/mp2t","Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, HEAD, OPTIONS","Access-Control-Allow-Headers":"*"}); if(req.method==="HEAD"){res.end();return;} res.send(Buffer.from(await upstream.arrayBuffer())); }catch(e){res.status(502).send(`CDN proxy error: ${(e as Error).message}`)} });

router.get("/animeworld/resolve", async(req:Request,res:Response)=>{ const player=String(req.query.url||""); const m=player.match(/\/video\/([A-Za-z0-9_-]+)/i); if(!m){res.status(404).send("No video id");return;} const id=m[1]!; try{const u=new URL(player); const r=await fetchUp(`${u.origin}/player/index.php?data=${encodeURIComponent(id)}&do=getVideo`,{method:"POST",headers:{Referer:player,"X-Requested-With":"XMLHttpRequest","Content-Type":"application/x-www-form-urlencoded"},body:`hash=${encodeURIComponent(id)}&r=${encodeURIComponent(player)}`}); if(!r.ok){res.status(r.status).send("Player API failed");return;} const data=await r.json() as Record<string,unknown>; const raw=String(data.securedLink||data.videoSource||""); if(!raw){res.status(404).send("No stream");return;} res.redirect(`${appUrl(req, "/animeworld/proxy")}?url=${encodeURIComponent(raw)}`); }catch(e){res.status(502).send(`Resolve error: ${(e as Error).message}`)} });

function b64json(value:string){ const pad="=".repeat((4-value.length%4)%4); return JSON.parse(Buffer.from(value.replace(/ /g,"+"),"base64url").toString()); }
function normalizeAbyss(u:string){ try{const x=new URL(u); const h=x.hostname.toLowerCase(); if(h==="abysscdn.com"){const v=x.searchParams.get("v"); return v?`https://play.abyssplayer.com/${v}`:null;} if((h==="abyssplayer.com"||h==="www.abyssplayer.com"||h==="play.abyssplayer.com"||h==="player.abyssplayer.com")&&x.pathname!=="/")return u; return null;}catch{return null;} }
function md5(s:string){return createHash("md5").update(s).digest();}
function decryptMedia(html:string){ const m=html.match(/const\s+datas\s*=\s*"([^"]+)"/); if(!m)return null; try{const raw=Buffer.from(m[1]!,"base64").toString("latin1"); const datas=JSON.parse(raw); const enc=Buffer.from(Array.from(datas.media as string).map((c:string)=>c.charCodeAt(0))); const key=Buffer.from(createHash("md5").update(`${datas.user_id}:${datas.slug}:${datas.md5_id}`).digest("hex")); const iv=key.subarray(0,16); const d=awaitlessCipher(key,iv,enc); const media=JSON.parse(d.toString("utf8")); media.md5_id=datas.md5_id; media.slug=datas.slug; return media;}catch{return null;} }
function awaitlessCipher(key:Buffer,iv:Buffer,data:Buffer){ const c=createCipheriv("aes-256-ctr",key,iv); return Buffer.concat([c.update(data),c.final()]); }
function token(size:number,md5id:number,resid:number,index:number){ const sizeBytes=Buffer.from(String(size).split("").map(Number)); const key=Buffer.from(createHash("md5").update(sizeBytes).digest("hex")); const path=`/mp4/${md5id}/${resid}/${size}/${CHUNK}/${index}`; const c=createCipheriv("aes-256-ctr",key,key.subarray(0,16)); const enc=c.update(Buffer.from(path)); return Buffer.from(enc.toString("base64").replace(/=+$/,""),"utf8").toString("base64").replace(/=+$/g,""); }
function sign(value:string){return createHmac("sha256",SECRET).update(value).digest("hex");}
function encodeSource(source:Record<string,unknown>){const s=Buffer.from(JSON.stringify(source)).toString("base64url").replace(/=+$/g,""); return `${s}`;}
function decodeSource(value:string){try{return JSON.parse(Buffer.from(value,"base64url").toString("utf8")) as Record<string,unknown>}catch{return null;}}
function rangeFor(h:string|undefined,size:number){ if(!h||!h.startsWith("bytes="))return [0,size-1]; const q=h.slice(6).split(","); if(q.length!==1)throw new Error("range"); const [a,b]=q[0]!.split("-"); let start,end;if(!a){const n=Number(b);start=Math.max(size-n,0);end=size-1;}else{start=Number(a);end=b?Math.min(Number(b),size-1):size-1;} if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||start>=size||end<start)throw new Error("range"); return [start,end]; }

router.get("/animeworld/abyss", async(req:Request,res:Response)=>{ const player=String(req.query.url||""); if(!/^https?:\/\//i.test(player)){res.status(400).send("Invalid player");return;} try{ const discovered:string[]=[]; const add=(u:string)=>{const n=normalizeAbyss(u);if(n&&!discovered.includes(n))discovered.push(n)}; const collect=(text:string)=>{for(const m of text.matchAll(/https?:\/\/(?:(?:play|player)\.abyssplayer\.com|(?:www\.)?abyssplayer\.com)\/[A-Za-z0-9_-]+(?:\?[^\"'\s<]*)?/gi))add(m[0]); for(const m of text.matchAll(/https?:\/\/(?:www\.)?abysscdn\.com\/\?v=([A-Za-z0-9_-]+)/gi))add(`https://play.abyssplayer.com/${m[1]}`)}; const r=await fetchUp(player,{headers:{Referer:"https://watchanimeworld.top/"}}); const html=await r.text(); add(r.url); collect(html); const q=new URL(player).searchParams.get("data"); if(q){try{const entries=b64json(q); if(Array.isArray(entries))for(const e of entries){if(!e||typeof e.link!=="string")continue; const direct=normalizeAbyss(e.link); if(direct){add(direct);continue;} try{const lr=await fetchUp(e.link,{headers:{Referer:player}}); add(lr.url); collect(await lr.text());}catch{}}}catch{}} for(const page of discovered){const pr=await fetchUp(page,{headers:{Referer:player}}); const ph=await pr.text(); const media=decryptMedia(ph); if(!media)continue; const mp4=media.mp4||{}; const domains=mp4.domains||[]; const domain=String(domains[0]||""); const suffix=domain.includes(".")?domain.split(".").slice(1).join("."):domain; const sources=Array.isArray(mp4.sources)?mp4.sources:[]; for(const source of sources){if(!source||source.status===false||!source.res_id||!source.size)continue; const host=`${source.sub}.${suffix}`.toLowerCase(); if(!ABYSS_SUFFIXES.some(x=>host.endsWith(x)))continue; const payload={host,slug:media.slug,md5_id:Number(media.md5_id),res_id:Number(source.res_id),size:Number(source.size)}; const encoded=encodeSource(payload); const sig=sign(encoded); res.redirect(`${appUrl(req, "/animeworld/cdn/abyss/stream")}?source=${encodeURIComponent(encoded)}&sig=${sig}`); return;} } res.status(404).send("No Abyss media found"); }catch(e){res.status(502).send(`Abyss error: ${(e as Error).message}`)} });

router.get("/animeworld/cdn/abyss/stream", async(req:Request,res:Response)=>{ const encoded=String(req.query.source||""); const sig=String(req.query.sig||""); if(!encoded||!sig){res.status(400).send("Missing source");return;} const expected=sign(encoded); if(expected.length!==sig.length||!timingSafeEqual(Buffer.from(expected),Buffer.from(sig))){res.status(403).send("Forbidden");return;} const source=decodeSource(encoded); if(!source){res.status(400).send("Invalid source");return;} const host=String(source.host||""); if(!ABYSS_SUFFIXES.some(x=>host.endsWith(x))){res.status(400).send("Invalid host");return;} const size=Number(source.size), md5id=Number(source.md5_id), resid=Number(source.res_id); if(!size||!md5id||!resid){res.status(400).send("Invalid source");return;} try{const [start,end]=rangeFor(req.headers.range,size); const first=Math.floor(start/CHUNK),last=Math.floor(end/CHUNK); const pieces:Buffer[]=[]; for(let i=first;i<=last;i++){const u=`https://${host}/sora/${size}/${token(size,md5id,resid,i)}`; const r=await fetchUp(u,{headers:{Referer:"https://abysscdn.com/"}}); if(!r.ok)throw new Error(`chunk ${r.status}`); const b=Buffer.from(await r.arrayBuffer()); const chunkStart=i*CHUNK; const left=Math.max(start-chunkStart,0),right=Math.min(end-chunkStart+1,b.length); if(right>left)pieces.push(b.subarray(left,right));} const body=Buffer.concat(pieces); res.status(req.headers.range?206:200).set({"Content-Type":"video/mp4","Content-Length":String(body.length),"Accept-Ranges":"bytes","Content-Range":`bytes ${start}-${end}/${size}`,"Access-Control-Allow-Origin":"*"}).send(body); }catch(e){res.status(502).send(`Abyss stream error: ${(e as Error).message}`)} });

export default router;
